AIRLINE_MAPPING = {
    "華航": "中華航空", "中華": "中華航空", "虎航": "台灣虎航", "長榮": "長榮航空", "星宇": "星宇航空",
    "日本": "日本航空", "全日本": "全日本空輸", "全日空": "全日本空輸", "捷星日本": "捷星日本航空", "捷星": "捷星日本航空", "樂桃": "樂桃航空",
    "山東": "山東航空", "中國東方": "中國東方航空", "中國南方": "中國南方航空", "中國國際": "中國國際", "四川": "四川航空", "春秋": "春秋航空", "海南": "海南航空", "深圳": "深圳航空", "廈門": "廈門航空",
    "大韓": "大韓航空", "可依": "可依航空", "易斯達": "易斯達航空", "首爾": "首爾航空", "真": "真航空", "釜山": "釜山航空", "德威": "德威航空", "濟州": "濟州航空", "韓亞": "韓亞航空",
    "越竹": "越竹航空", "越南": "越南航空", "越旅": "越旅航空", "越捷": "越捷航空",
    "大灣區": "大灣區航空", "香港快運": "香港快運航空", "香港": "香港航空", "國泰": "國泰航空",
    "泰國亞洲": "泰國亞洲航空", "泰國": "泰國航空", "泰國獅子": "泰國獅子航空", "泰國越捷": "泰國越捷航空",
    "達美": "達美航空", "聯合": "聯合航空",
    "新加坡": "新加坡航空", "酷": "酷航空", 
    "澳門": "澳門航空", 
    "馬來西亞": "馬來西亞航空", "亞洲": "亞洲航空"
}

AIRPORT_MAPPING = {
    "松山": "臺北松山機場",
    "松山機": "臺北松山機場",
    "台北": "臺北松山機場",
    "臺北": "臺北松山機場",
    "桃園": "桃園國際機場",
    "桃機": "桃園國際機場",
    "台中": "臺中國際機場",
    "臺中": "臺中國際機場",
    "高雄": "高雄國際航空站",
    "高雄國際機場": "高雄國際航空站",
    "小港": "高雄國際航空站",
    "小港國際機場": "高雄國際航空站",
    "東京": "東京國際機場",
    "成田": "成田國際機場",
    "名古屋": "中部國際機場",
    "大阪": "大阪國際機場",
    "關西": "關西國際機場",
    "福岡": "福岡機場",
    "新千歲": "新千歲機場",
    "函館": "函館機場",
    "仙台": "仙台機場",
    "新潟": "新潟機場",
    "廣島": "廣島機場",
    "高松": "高松機場",
    "松山空港": "松山機場",
    "高知": "高知機場",
    "北九州": "北九州機場",
    "長崎": "長崎機場",
    "熊本": "熊本機場",
    "大分": "大分機場",
    "宮崎": "宮崎機場",
    "鹿兒島": "鹿兒島機場",
    "那霸": "那霸機場",
    "旭川": "旭川機場",
    "秋田": "秋田機場",
    "青森": "青森機場",
    "女滿別": "女滿別機場",
    "花卷": "花卷機場",
    "福島": "福島機場",
    "富山": "富山機場",
    "靜岡": "靜岡機場",
    "神戶": "神戶機場",
    "岡山": "岡山機場",
    "佐賀": "佐賀機場",
    "下地島": "下地島機場",
    "茨城": "茨城機場",
    "小松": "小松機場",
    "美保": "美保機場",
    "德島": "德島機場",
    "北京首都": "北京首都國際機場",
    "北京大興": "北京大興國際機場",
    "大興機場": "北京大興國際機場",
    "天津濱海": "天津濱海國際機場",
    "天津機場": "天津濱海國際機場",
    "濱海機場": "天津濱海國際機場",
    "石家莊正定": "石家莊正定國際機場",
    "石家莊": "石家莊正定國際機場",
    "秦皇島北戴河": "秦皇島北戴河機場",
    "太原武宿": "太原武宿國際機場",
    "武宿機場": "太原武宿國際機場",
    "大同雲岡": "大同雲岡國際機場",
    "雲岡機場": "大同雲岡國際機場",
    "運城鹽湖": "運城鹽湖國際機場",
    "鄂爾多斯伊金霍洛": "鄂爾多斯伊金霍洛國際機場",
    "瀋陽桃仙": "瀋陽桃仙國際機場",
    "呼倫貝爾海拉爾": "呼倫貝爾海拉爾機場",
    "大連周水子": "大連周水子國際機場",
    "哈爾濱太平": "哈爾濱太平國際機場",
    "佳木斯東郊": "佳木斯東郊機場",
    "上海虹橋": "上海虹橋國際機場",
    "虹橋": "上海虹橋國際機場",
    "虹橋機場": "上海虹橋國際機場",
    "上海浦東": "上海浦東國際機場",
    "浦東": "上海浦東國際機場",
    "浦東機場": "上海浦東國際機場",
    "南京祿口": "南京祿口國際機場",
    "祿口機場": "南京祿口國際機場",
    "無錫碩放": "無錫碩放機場",
    "徐州觀音": "徐州觀音國際機場",
    "觀音機場": "徐州觀音國際機場",
    "常州奔牛": "常州奔牛國際機場",
    "南通興東": "南通興東國際機場",
    "興東機場": "南通興東國際機場",
    "連雲港花果山": "連雲港花果山國際機場",
    "淮安漣水": "淮安漣水國際機場",
    "漣水機場": "淮安漣水國際機場",
    "鹽城南洋": "鹽城南洋國際機場",
    "南洋機場": "鹽城南洋國際機場",
    "揚州泰州": "揚州泰州國際機場",
    "泰州機場": "揚州泰州國際機場",
    "杭州蕭山": "杭州蕭山國際機場",
    "蕭山機場": "杭州蕭山國際機場",
    "寧波櫟社": "寧波櫟社國際機場",
    "溫州龍灣": "溫州龍灣國際機場",
    "龍灣機場": "溫州龍灣國際機場",
    "義烏": "義烏機場",
    "舟山普陀山": "舟山普陀山國際機場",
    "合肥新橋": "合肥新橋國際機場",
    "黃山屯溪": "黃山屯溪國際機場",
    "福州長樂": "福州長樂國際機場",
    "長樂機場": "福州長樂國際機場",
    "廈門高崎": "廈門高崎國際機場",
    "高崎機場": "廈門高崎國際機場",
    "泉州晉江": "泉州晉江國際機場",
    "晉江機場": "泉州晉江國際機場",
    "武夷山": "武夷山機場",
    "南昌昌北": "南昌昌北國際機場",
    "昌北機場": "南昌昌北國際機場",
    "濟南遙牆": "濟南遙牆國際機場",
    "遙牆機場": "濟南遙牆國際機場",
    "青島膠東": "青島膠東國際機場",
    "煙臺蓬萊": "煙臺蓬萊國際機場",
    "威海大水泊": "威海大水泊國際機場",
    "臨沂啟陽": "臨沂啟陽國際機場",
    "鄭州新鄭": "鄭州新鄭國際機場",
    "洛陽北郊": "洛陽北郊機場",
    "北郊機場": "洛陽北郊機場",
    "恩施許家坪": "恩施許家坪國際機場",
    "鄂州花湖": "鄂州花湖國際機場",
    "武漢天河": "武漢天河國際機場",
    "天河機場": "武漢天河國際機場",
    "宜昌三峽": "宜昌三峽國際機場",
    "長沙黃花": "長沙黃花國際機場",
    "黃花機場": "長沙黃花國際機場",
    "張家界荷花": "張家界荷花國際機場",
    "廣州白雲": "廣州白雲國際機場",
    "白雲機場": "廣州白雲國際機場",
    "深圳寶安": "深圳寶安國際機場",
    "寶安機場": "深圳寶安國際機場",
    "湛江吳川": "湛江吳川國際機場",
    "吳川機場": "湛江吳川國際機場",
    "梅州梅縣": "梅州梅縣機場",
    "梅縣機場": "梅州梅縣機場",
    "揭陽潮汕": "揭陽潮汕國際機場",
    "南寧吳圩": "南寧吳圩國際機場",
    "桂林兩江": "桂林兩江國際機場",
    "兩江機場": "桂林兩江國際機場",
    "北海福成": "北海福成機場",
    "福成機場": "北海福成機場",
    "海口美蘭": "海口美蘭國際機場",
    "美蘭機場": "海口美蘭國際機場",
    "三亞鳳凰": "三亞鳳凰國際機場",
    "鳳凰機場": "三亞鳳凰國際機場",
    "瓊海博鰲": "瓊海博鰲國際機場",
    "瓊海機場": "瓊海博鰲國際機場",
    "博鰲機場": "瓊海博鰲國際機場",
    "重慶江北": "重慶江北國際機場",
    "江北機場": "重慶江北國際機場",
    "成都天府": "成都天府國際機場",
    "天府機場": "成都天府國際機場",
    "貴陽龍洞堡": "貴陽龍洞堡國際機場",
    "昆明長水": "昆明長水國際機場",
    "長水機場": "昆明長水國際機場",
    "麗江三義": "麗江三義國際機場",
    "西雙版納嘎灑": "西雙版納嘎灑國際機場",
    "西安咸陽": "西安咸陽國際機場",
    "咸陽機場": "西安咸陽國際機場",
    "蘭州中川": "蘭州中川國際機場",
    "中川機場": "蘭州中川國際機場",
    "西寧曹家堡": "西寧曹家堡國際機場",
    "銀川河東": "銀川河東國際機場",
    "烏魯木齊天山": "烏魯木齊天山國際機場",
    "清州": "清州國際機場",
    "清州機場": "清州國際機場",
    "大邱機場": "大邱國際機場",
    "大邱": "大邱國際機場",
    "金浦機場": "金浦國際機場",
    "金浦": "金浦國際機場",
    "仁川機場": "仁川國際機場",
    "仁川": "仁川國際機場",
    "濟州機場": "濟州國際機場",
    "濟州": "濟州國際機場",
    "務安機場": "務安國際機場",
    "務安": "務安國際機場",
    "金海機場": "金海國際機場",
    "金海": "金海國際機場",
    "襄陽機場": "襄陽國際機場",
    "襄陽": "襄陽國際機場",
    "峴港機場": "峴港國際機場",
    "峴港": "峴港國際機場",
    "雲屯機場": "雲屯國際機場",
    "雲屯": "雲屯國際機場",
    "吉碑機場": "吉碑國際機場",
    "吉碑": "吉碑國際機場",
    "內排機場": "內排國際機場",
    "內排": "內排國際機場",
    "新山一機場": "新山一國際機場",
    "新山一": "新山一國際機場",
    "金蘭機場": "金蘭國際機場",
    "金蘭": "金蘭國際機場",
    "富國機場": "富國國際機場",
    "富國": "富國國際機場",
    "蓮姜": "蓮姜機場",
    "榮市機場": "榮市國際機場",
    "榮市": "榮市國際機場",
    "芹苴機場": "芹苴國際機場",
    "芹苴": "芹苴國際機場",
    "富牌機場": "富牌國際機場",
    "富牌": "富牌國際機場",
    "香港機場": "香港國際機場",
    "香港": "香港國際機場",
    "蘇凡納布機場": "蘇凡納布機場",
    "蘇凡納布": "蘇凡納布機場",
    "廊曼機場": "廊曼國際機場",
    "廊曼": "廊曼國際機場",
    "清邁機場": "清邁國際機場",
    "清邁": "清邁國際機場",
    "清萊機場": "清萊國際機場",
    "清萊": "清萊國際機場",
    "合艾機場": "合艾國際機場",
    "合艾": "合艾國際機場",
    "蘇梅機場": "蘇梅國際機場",
    "蘇梅": "蘇梅國際機場",
    "喀比機場": "喀比國際機場",
    "喀比": "喀比國際機場",
    "布吉機場": "布吉國際機場",
    "布吉": "布吉國際機場",
    "烏打拋機場": "烏打拋國際機場",
    "烏打拋": "烏打拋國際機場",
    "素叻他尼": "素叻他尼國際機場",
    "沙特爾斯沃思機場": "伯明罕-沙特爾斯沃思國際機場",
    "沙特爾斯沃思": "伯明罕-沙特爾斯沃思國際機場",
    "史蒂文斯安克拉治機場": "泰德·史蒂文斯安克拉治國際機場 ",
    "史蒂文斯安克拉治": "泰德·史蒂文斯安克拉治國際機場 ",
    "費爾班克斯機場": "費爾班克斯國際機場",
    "費爾班克斯": "費爾班克斯國際機場",
    "鳳凰城天港機場": "鳳凰城天港國際機場",
    "鳳凰城天港": "鳳凰城天港國際機場",
    "長灘機場": "長灘機場",
    "長灘": "長灘機場",
    "洛杉磯機場": "洛杉磯國際機場",
    "洛杉磯": "洛杉磯國際機場",
    "舊金山灣區奧克蘭機場": "舊金山灣區奧克蘭國際機場",
    "舊金山灣區奧克蘭": "舊金山灣區奧克蘭國際機場",
    "安大略機場": "安大略國際機場",
    "安大略": "安大略國際機場",
    "棕櫚泉機場": "棕櫚泉國際機場",
    "棕櫚泉": "棕櫚泉國際機場",
    "沙加緬度機場": "沙加緬度國際機場",
    "沙加緬度": "沙加緬度國際機場",
    "聖地牙哥機場": "聖地牙哥國際機場",
    "聖地牙哥": "聖地牙哥國際機場",
    "舊金山機場": "舊金山國際機場",
    "舊金山": "舊金山國際機場",
    "峰田聖荷西機場": "諾曼·峰田聖荷西國際機場",
    "峰田聖荷西": "諾曼·峰田聖荷西國際機場",
    "峰田": "諾曼·峰田聖荷西國際機場",
    "峰田機場": "諾曼·峰田聖荷西國際機場",
    "聖荷西": "諾曼·峰田聖荷西國際機場",
    "聖荷西機場": "諾曼·峰田聖荷西國際機場",
    "韋恩機場": "約翰韋恩機場",
    "韋恩": "約翰韋恩機場",
    "丹佛機場": "丹佛國際機場",
    "丹佛": "丹佛國際機場",
    "邁阿密機場": "邁阿密國際機場",
    "邁阿密": "邁阿密國際機場",
    "坦帕機場": "坦帕國際機場",
    "坦帕": "坦帕國際機場",
    "傑克遜亞特蘭大機場": "哈茨菲爾德-傑克遜亞特蘭大國際機場",
    "傑克遜亞特蘭大": "哈茨菲爾德-傑克遜亞特蘭大國際機場",
    "傑克遜": "哈茨菲爾德-傑克遜亞特蘭大國際機場",
    "傑克遜機場": "哈茨菲爾德-傑克遜亞特蘭大國際機場",
    "哈茨菲爾德機場": "哈茨菲爾德-傑克遜亞特蘭大國際機場",
    "哈茨菲爾德": "哈茨菲爾德-傑克遜亞特蘭大國際機場",
    "亞特蘭大": "哈茨菲爾德-傑克遜亞特蘭大國際機場",
    "亞特蘭大機場": "哈茨菲爾德-傑克遜亞特蘭大國際機場",
    "井上機場": "丹尼爾·K·井上國際機場",
    "井上": "丹尼爾·K·井上國際機場",
    "丹尼爾機場": "丹尼爾·K·井上國際機場",
    "丹尼爾": "丹尼爾·K·井上國際機場",
    "歐海爾機場": "歐海爾國際機場",
    "歐海爾": "歐海爾國際機場",
    "中途機場": "中途國際機場",
    "中途": "中途國際機場",
    "印第安納波利斯機場": "印第安納波利斯國際機場",
    "印第安納波利斯": "印第安納波利斯國際機場",
    "狄蒙機場": "狄蒙國際機場",
    "狄蒙": "狄蒙國際機場",
    "辛辛那提機場": "辛辛那提/北肯塔基國際機場",
    "辛辛那提": "辛辛那提/北肯塔基國際機場",
    "北肯塔基機場": "辛辛那提/北肯塔基國際機場",
    "北肯塔基": "辛辛那提/北肯塔基國際機場",
    "紐奧良路易阿姆斯壯機場": "紐奧良路易阿姆斯壯國際機場",
    "紐奧良路易阿姆斯壯": "紐奧良路易阿姆斯壯國際機場",
    "阿姆斯壯機場": "紐奧良路易阿姆斯壯國際機場",
    "阿姆斯壯": "紐奧良路易阿姆斯壯國際機場",
    "紐奧良機場": "紐奧良路易阿姆斯壯國際機場",
    "紐奧良": "紐奧良路易阿姆斯壯國際機場",
    "路易阿姆斯壯機場": "紐奧良路易阿姆斯壯國際機場",
    "路易阿姆斯壯": "紐奧良路易阿姆斯壯國際機場",
    "巴爾的摩機場": "巴爾的摩/華盛頓瑟古德·馬歇爾國際機場",
    "巴爾的摩": "巴爾的摩/華盛頓瑟古德·馬歇爾國際機場",
    "華盛頓瑟古德機場": "巴爾的摩/華盛頓瑟古德·馬歇爾國際機場",
    "華盛頓瑟古德": "巴爾的摩/華盛頓瑟古德·馬歇爾國際機場",
    "馬歇爾機場": "巴爾的摩/華盛頓瑟古德·馬歇爾國際機場",
    "馬歇爾": "巴爾的摩/華盛頓瑟古德·馬歇爾國際機場",
    "愛德華·勞倫斯·洛根將軍機場": "愛德華·勞倫斯·洛根將軍國際機場",
    "愛德華·勞倫斯·洛根將軍": "愛德華·勞倫斯·洛根將軍國際機場",
    "愛德華機場": "愛德華·勞倫斯·洛根將軍國際機場",
    "愛德華": "愛德華·勞倫斯·洛根將軍國際機場",
    "勞倫斯機場": "愛德華·勞倫斯·洛根將軍國際機場",
    "勞倫斯": "愛德華·勞倫斯·洛根將軍國際機場",
    "波士頓機場": "愛德華·勞倫斯·洛根將軍國際機場",
    "波士頓": "愛德華·勞倫斯·洛根將軍國際機場",
    "波士頓洛根機場": "愛德華·勞倫斯·洛根將軍國際機場",
    "波士頓洛根": "愛德華·勞倫斯·洛根將軍國際機場",
    "底特律都會韋恩縣": "底特律都會韋恩縣機場",
    "底特律大都會機場": "底特律都會韋恩縣機場",
    "底特律大都會": "底特律都會韋恩縣機場",
    "底特律機場": "底特律都會韋恩縣機場",
    "底特律": "底特律都會韋恩縣機場",
    "都會韋恩機場": "底特律都會韋恩縣機場",
    "都會韋恩": "底特律都會韋恩縣機場",
    "聖路易斯蘭伯特": "聖路易斯蘭伯特國際機場",
    "聖路易斯機場": "聖路易斯蘭伯特國際機場",
    "聖路易斯": "聖路易斯蘭伯特國際機場",
    "蘭伯特機場": "聖路易斯蘭伯特國際機場",
    "蘭伯特": "聖路易斯蘭伯特國際機場",
    "哈利瑞德機場": "哈利·瑞德國際機場",
    "哈利瑞德": "哈利·瑞德國際機場",
    "紐華克自由": "紐華克自由國際機場",
    "紐瓦克機場": "紐華克自由國際機場",
    "紐瓦克": "紐華克自由國際機場",
    "阿布奎基機場": "阿布奎基國際機場",
    "阿布奎基": "阿布奎基國際機場",
    "約翰甘迺迪機場": "約翰·甘迺迪國際機場",
    "約翰甘迺迪": "約翰·甘迺迪國際機場",
    "甘迺迪機場": "約翰·甘迺迪國際機場",
    "甘迺迪": "約翰·甘迺迪國際機場",
    "克里夫蘭霍普金斯": "克里夫蘭霍普金斯國際機場",
    "克里夫蘭機場": "克里夫蘭霍普金斯國際機場",
    "克里夫蘭": "克里夫蘭霍普金斯國際機場",
    "霍普金斯機場": "克里夫蘭霍普金斯國際機場",
    "霍普金斯": "克里夫蘭霍普金斯國際機場",
    "約翰格倫哥倫布機場": "約翰·格倫哥倫布國際機場",
    "約翰格倫哥倫布": "約翰·格倫哥倫布國際機場",
    "格倫哥倫布機場": "約翰·格倫哥倫布國際機場",
    "格倫哥倫布": "約翰·格倫哥倫布國際機場",
    "波特蘭": "波特蘭國際機場",
    "費城": "費城國際機場",
    "匹茲堡": "匹茲堡國際機場",
    "羅德島機場": "羅德島T·F·格林國際機場",
    "羅德島": "羅德島T·F·格林國際機場",
    "羅德島格林機場": "羅德島T·F·格林國際機場",
    "羅德島格林": "羅德島T·F·格林國際機場",
    "格林機場": "羅德島T·F·格林國際機場",
    "格林": "羅德島T·F·格林國際機場",
    "奧斯汀伯格史東機場": "奧斯汀-伯格史東國際機場",
    "奧斯汀伯格史東": "奧斯汀-伯格史東國際機場",
    "奧斯汀機場": "奧斯汀-伯格史東國際機場",
    "奧斯汀": "奧斯汀-伯格史東國際機場",
    "伯格史東機場": "奧斯汀-伯格史東國際機場",
    "伯格史東": "奧斯汀-伯格史東國際機場",
    "達拉斯機場": "達拉斯/沃斯堡國際機場",
    "達拉斯": "達拉斯/沃斯堡國際機場",
    "沃斯堡機場": "達拉斯/沃斯堡國際機場",
    "沃斯堡": "達拉斯/沃斯堡國際機場",
    "達拉斯沃斯堡機場": "達拉斯/沃斯堡國際機場",
    "達拉斯沃斯堡": "達拉斯/沃斯堡國際機場",
    "喬治布希洲機場": "喬治·布希洲際機場",
    "喬治布希洲": "喬治·布希洲際機場",
    "喬治機場": "喬治·布希洲際機場",
    "喬治": "喬治·布希洲際機場",
    "布希洲機場": "喬治·布希洲際機場",
    "布希洲": "喬治·布希洲際機場",
    "聖安東尼奧機場": "聖安東尼奧國際機場",
    "聖安東尼奧": "聖安東尼奧國際機場",
    "鹽湖城機場": "鹽湖城國際機場",
    "鹽湖城": "鹽湖城國際機場",
    "諾福克機場": "諾福克國際機場",
    "諾福克": "諾福克國際機場",
    "里契蒙機場": "里契蒙國際機場",
    "里契蒙": "里契蒙國際機場",
    "隆納雷根華盛頓機場": "隆納·雷根華盛頓國家機場",
    "隆納雷根華盛頓": "隆納·雷根華盛頓國家機場",
    "隆納雷根機場": "隆納·雷根華盛頓國家機場",
    "隆納雷根": "隆納·雷根華盛頓國家機場",
    "雷根華盛頓機場": "隆納·雷根華盛頓國家機場",
    "雷根華盛頓": "隆納·雷根華盛頓國家機場",
    "華盛頓杜勒斯機場": "華盛頓杜勒斯國際機場",
    "華盛頓杜勒斯": "華盛頓杜勒斯國際機場",
    "杜勒斯機場": "華盛頓杜勒斯國際機場",
    "杜勒斯": "華盛頓杜勒斯國際機場",
    "西雅圖塔科馬機場": "西雅圖-塔科馬國際機場",
    "西雅圖塔科馬": "西雅圖-塔科馬國際機場",
    "西雅圖機場": "西雅圖-塔科馬國際機場",
    "西雅圖": "西雅圖-塔科馬國際機場",
    "塔科馬機場": "西雅圖-塔科馬國際機場",
    "塔科馬": "西雅圖-塔科馬國際機場",
    "亨丁頓三州": "亨丁頓三州機場",
    "拉勒米區域": "拉勒米區域機場",
    "謝里登": "謝里登機場",
    "安東尼奧汪帕特機場": "安東尼奧·汪帕特國際機場",
    "安東尼奧汪帕特": "安東尼奧·汪帕特國際機場",
    "汪帕特機場": "安東尼奧·汪帕特國際機場",
    "汪帕特": "安東尼奧·汪帕特國際機場",
    "塞班機場": "塞班國際機場",
    "路易斯穆尼奧斯馬林機場": "路易斯·穆尼奧斯·馬林國際機場",
    "路易斯穆尼奧斯馬林": "路易斯·穆尼奧斯·馬林國際機場",
    "穆尼奧斯馬林機場": "路易斯·穆尼奧斯·馬林國際機場",
    "穆尼奧斯馬林": "路易斯·穆尼奧斯·馬林國際機場",
    "穆尼奧斯機場": "路易斯·穆尼奧斯·馬林國際機場",
    "穆尼奧斯": "路易斯·穆尼奧斯·馬林國際機場",
    "新加坡樟宜機場": "新加坡樟宜國際機場",
    "新加坡樟宜": "新加坡樟宜國際機場",
    "樟宜機場": "新加坡樟宜國際機場",
    "樟宜": "新加坡樟宜國際機場",
    "新加坡機場": "新加坡樟宜國際機場",
    "新加坡": "新加坡樟宜國際機場",
    "實里達": "實里達機場",
    "澳門機場": "澳門國際機場",
    "澳門": "澳門國際機場",
    "蘭卡威機場": "蘭卡威國際機場",
    "蘭卡威": "蘭卡威國際機場",
    "檳城機場": "檳城國際機場",
    "檳城": "檳城國際機場",
    "怡保機場": "怡保國際機場",
    "怡保": "怡保國際機場",
    "蘇丹阿末沙": "蘇丹阿末沙機場",
    "吉隆坡機場": "吉隆坡國際機場",
    "吉隆坡": "吉隆坡國際機場",
    "亞庇機場": "亞庇國際機場",
    "亞庇": "亞庇國際機場",
    "蘇丹阿都阿兹沙": "蘇丹阿都阿兹沙機場",
    "馬六甲機場": "馬六甲國際機場",
    "馬六甲": "馬六甲國際機場",
    "士乃機場": "士乃國際機場",
    "士乃": "士乃國際機場",
    "斗湖": "斗湖機場",
    "古晉機場": "古晉國際機場",
    "古晉": "古晉國際機場",
    "美里": "美里機場",
}

CUSTOM_MAPPING = {
    "松山": "台北關",
    "台北": "台北關",
    "臺北": "台北關",
    "桃園": "台北關",
    "台中": "台中關",
    "臺中": "台中關",
    "高雄": "高雄關",
    "小港": "高雄關"
}

COUNTRY_MAPPING = {
    "日本": "日本",
    "中國": "中國",
    "大陸": "中國",
    "南韓": "南韓",
    "韓國": "南韓",
    "越南": "越南",
    "香港": "香港",
    "泰國": "泰國",
    "美國": "美國",
    "新加坡": "新加坡",
    "澳門": "澳門",
    "馬來西亞": "馬來西亞"
}

URL_MAP = {
    "臺中國際機場": ["https://www.tca.gov.tw/"],
    "臺北松山機場": ["https://www.tsa.gov.tw/","https://www.facebook.com/TSA.tw"],
    "桃園國際機場": ["https://www.taoyuan-airport.com/","https://www.taoyuan-airport.com/1?p=1&k=&s=&e=","https://www.facebook.com/TIAfans"],
    "高雄國際航空站": ["https://www.kia.gov.tw/","https://airport.altob.com.tw/app/map;siteId=10502","https://www.facebook.com/khhairport"],
    "東京國際機場":["https://tokyo-haneda.com/zh-CHT/"],
    "成田國際機場":["https://www.narita-airport.jp/zh-sc/"],
    "中部國際機場":["https://www.centrair.jp/tzh/"],
    "大阪國際機場":["https://www.osaka-airport.co.jp/"],
    "關西國際機場":["https://www.kansai-airport.or.jp/"],
    "福岡機場":["https://www.fukuoka-airport.jp/tw/"],
    "新千歲機場":["https://www.hokkaido-airports.com/zh-CHT/"],
    "函館機場":["https://www.hokkaido-airports.com/zh-CHT/hakodate/"],
    "仙台機場":["https://www.sendai-airport.co.jp/cn/"],
    "新潟機場":["https://www.niigata-airport.gr.jp/"],
    "廣島機場":["https://www.hij.airport.jp/tw/"],
    "高松機場":["https://www.takamatsu-airport.com/"],
    "松山機場":["https://www.matsuyama-airport.co.jp/"],
    "高知機場":["https://www.kochiap.co.jp/"],
    "北九州機場":["https://www.kitakyu-air.jp/"],
    "長崎機場":["https://nagasaki-airport.jp/"],
    "熊本機場":["https://www.kumamoto-airport.co.jp/zh-TW/"],
    "大分機場":["https://www.oita-airport.jp/tw/"],
    "宮崎機場":["https://www.miyazaki-airport.co.jp/"],
    "鹿兒島機場":["https://www.koj-ab.co.jp/"],
    "那霸機場":["https://www.naha-airport.co.jp/zh-hant/"],
    "旭川機場":["https://www.hokkaido-airports.com/zh-CHT/asahikawa/"],
    "秋田機場":["https://www.akita-airport.com/"],
    "青森機場":["https://www.aomori-airport.co.jp/"],
    "女滿別機場":["https://www.hokkaido-airports.com/zh-CHT/memanbetsu/"],
    "花卷機場":["https://www.hna-terminal.co.jp/"],
    "福島機場":["https://fks-ab.co.jp/"],
    "富山機場":["https://www.toyama-airport.co.jp/"],
    "靜岡機場":["https://www.mtfuji-shizuokaairport.jp/"],
    "神戶機場":["https://www.kairport.co.jp/"],
    "岡山機場":["https://www.okayama-airport.org/"],
    "佐賀機場":["https://saga-ab.jp/"],
    "下地島機場":["https://shimojishima.jp/"],
    "茨城機場":["https://www.ibaraki-airport.net/"],
    "小松機場":["https://www.komatsuairport.jp/"],
    "美保機場":["https://www.yonago-air.com/"],
    "德島機場":["https://www.tokushima-airport.co.jp/"],
    "新石垣機場":["https://www.ishigaki-airport.co.jp/"],
    "北京首都國際機場":["https://www.bcia.com.cn/"],
    "北京大興國際機場":["https://www.bdia.com.cn/"],
    "天津濱海國際機場":["http://www.tbia.cn/cn/"],
    "石家莊正定國際機場":["https://www.96360.com/"],
    "秦皇島北戴河機場":[""],
    "太原武宿國際機場":[""],
    "大同雲岡國際機場":[""],
    "運城鹽湖國際機場":[""],
    "鄂爾多斯伊金霍洛國際機場":["https://www.ordosairport.com/"],
    "呼倫貝爾海拉爾機場":[""],
    "瀋陽桃仙國際機場":["http://shenyang.customs.gov.cn/"],
    "大連周水子國際機場":["https://www.dlairport.com/"],
    "哈爾濱太平國際機場":[""],
    "佳木斯東郊機場":[""],
    "上海虹橋國際機場":["https://www.shanghaiairport.com/"],
    "上海浦東國際機場":["https://www.shairport.com/"],
    "南京祿口國際機場":["http://www.njiairport.com/"],
    "無錫碩放機場":["https://www.wuxiairport.com/"],
    "徐州觀音國際機場":["https://www.xzairport.com/"],
    "常州奔牛國際機場":["https://czjc.changzhou.gov.cn/"],
    "南通興東國際機場":["https://www.ntcaac.com/"],
    "連雲港花果山國際機場":[""],
    "淮安漣水國際機場":[""],
    "鹽城南洋國際機場":["http://www.yccas.com/"],
    "揚州泰州國際機場":[""],
    "杭州蕭山國際機場":["http://www.hzairport.com/"],
    "寧波櫟社國際機場":["http://www.zjsairport.com/"],
    "溫州龍灣國際機場":["https://www.wzair.cn/"],
    "義烏機場":[""],
    "舟山普陀山國際機場":[""],
    "合肥新橋國際機場":["https://www.hfairport.com/"],
    "黃山屯溪國際機場":[""],
    "福州長樂國際機場":["https://www.fuzhouairport.com.cn/"],
    "廈門高崎國際機場":["https://www.xiamenairport.com.cn/"],
    "泉州晉江國際機場":["https://www.qzair.com/"],
    "武夷山機場":["http://www.wysairport.com/c/"],
    "南昌昌北國際機場":[""],
    "濟南遙牆國際機場":[""],
    "青島膠東國際機場":["https://www.qdairport.com/"],
    "煙臺蓬萊國際機場":[""],
    "威海大水泊國際機場":["https://airwh.com/"],
    "臨沂啟陽國際機場":[""],
    "鄭州新鄭國際機場":["https://www.zhengzhou-airport.com/"],
    "洛陽北郊機場":[""],
    "恩施許家坪國際機場":["http://www.hbesairport.com/"],
    "鄂州花湖國際機場":[""],
    "武漢天河國際機場":["http://www.whairport.com/"],
    "宜昌三峽國際機場":[""],
    "長沙黃花國際機場":["https://www.hunanairport.cn/"],
    "張家界荷花國際機場":["https://www.hunanairport.cn/"],
    "廣州白雲國際機場":["https://www.baiyunairport.com/"],
    "深圳寶安國際機場":["https://www.szairport.com/"],
    "湛江吳川國際機場":["http://www.zjairport.cn/" ],
    "梅州梅縣機場":[""],
    "揭陽潮汕國際機場":["http://www.cs-airport.com/"],
    "南寧吳圩國際機場":["https://nn.airport.gx.cn/" ],
    "桂林兩江國際機場":["https://gl.airport.gx.cn/"],   
    "北海福成機場":["https://bh.airport.gx.cn/"], 
    "海口美蘭國際機場":["http://www.mlairport.com/"], 
    "三亞鳳凰國際機場":["https://www.sanyaairport.com/"], 
    "瓊海博鰲國際機場":[""],
    "重慶江北國際機場":["https://www.cqa.cn/"], 
    "成都天府國際機場":["https://www.sctfia.com/"], 
    "貴陽龍洞堡國際機場":["https://www.gzgyairport.com/"],
    "昆明長水國際機場":["https://km.ynairport.com/"],
    "麗江三義國際機場":[""],
    "西雙版納嘎灑國際機場":["https://bn.ynairport.com/"],
    "西安咸陽國際機場":["https://www.xxia.com/"],
    "蘭州中川國際機場":[""],
    "西寧曹家堡國際機場":[""],
    "銀川河東國際機場":["https://ningxia.cwag.com/"],
    "烏魯木齊天山國際機場":[""],
    "清州國際機場":["https://www.airport.co.kr/cheongju/"],
    "大邱國際機場":["https://www.airport.co.kr/daegu/"],
    "金浦國際機場":["https://www.airport.co.kr/gimpo/"],
    "仁川國際機場":["https://www.airport.kr/sites/ap_ch/index.do#section1"],
    "濟州國際機場":["https://www.airport.co.kr/jeju/"],
    "務安國際機場":["https://www.airport.co.kr/muan/"],
    "金海國際機場":["https://www.airport.co.kr/gimhae/"],
    "襄陽國際機場":["https://www.airport.co.kr/yangyang/"],
    "峴港國際機場":["https://danangairport.vn/"],
    "雲屯國際機場":["https://vdia.com.vn/"],
    "吉碑國際機場":["https://www.vietnamairport.vn/catbiairport/"],
    "內排國際機場":["https://noibaiairport.vn/"],
    "新山一國際機場":["https://tansonnhatairport.vn/"],
    "金蘭國際機場":["https://vietnamairport.vn/camranhairport/"],
    "富國國際機場":["https://www.vietnamairport.vn/phuquocairport/"],
    "蓮姜機場":["https://www.vietnamairport.vn/lienkhuongairport/"],
    "榮市國際機場":["https://vietnamairport.vn/vinhairport/"],
    "芹苴國際機場":["https://vietnamairport.vn/canthoairport/"],
    "富牌國際機場":["https://vietnamairport.vn/phubaiairport/"] ,
    "香港國際機場":["https://www.hongkongairport.com/"],
    "蘇凡納布機場":["https://suvarnabhumi.airportthai.co.th/"],
    "廊曼國際機場":["https://www.airportthai.co.th/"],
    "清邁國際機場":["https://chiangmai.airportthai.co.th/"],
    "清萊國際機場":["https://chiangrai.airportthai.co.th/"],
    "合艾國際機場":["https://hatyai.airportthai.co.th/"],
    "蘇梅國際機場":["https://www.samuiairport.com/"],
    "喀比國際機場":["https://minisite.airports.go.th/krabi/"],
    "布吉國際機場":["https://phuket.airportthai.co.th/"],
    "烏打拋國際機場":["https://www.utapao.com/th/"],
    "素叻他尼國際機場":["https://minisite.airports.go.th/suratthani/"],
    "伯明罕-沙特爾斯沃思國際機場":["https://www.flybirmingham.com/"],
    "泰德·史蒂文斯安克拉治國際機場 ":["https://dot.alaska.gov/anc/"],
    "費爾班克斯國際機場":["https://dot.alaska.gov/faiiap/"],
    "鳳凰城天港國際機場":["https://www.skyharbor.com/"],
    "長灘機場":[""],
    "洛杉磯國際機場":["https://www.flylax.com/"],
    "舊金山灣區奧克蘭國際機場":["https://www.iflyoak.com/"],
    "安大略國際機場":["https://www.flyontario.com/"],
    "棕櫚泉國際機場":["https://flypsp.com/"],
    "沙加緬度國際機場":["https://sacramento.aero/smf"],
    "聖地牙哥國際機場":["https://www.san.org/"],
    "舊金山國際機場":["https://www.flysfo.com/"],
    "諾曼·峰田聖荷西國際機場":["https://www.flysanjose.com/"],
    "約翰韋恩機場":["https://www.ocair.com/"],
    "丹佛國際機場":["https://www.flydenver.com/"],
    "邁阿密國際機場":["https://www.miami-airport.com/"],
    "坦帕國際機場":["https://www.tampaairport.com/"],
    "哈茨菲爾德-傑克遜亞特蘭大國際機場":["https://www.atl.com/"],
    "丹尼爾·K·井上國際機場":["https://hidot.hawaii.gov/"],
    "歐海爾國際機場":["https://www.flychicago.com/ohare/"],
    "中途國際機場":["https://www.flychicago.com/midway/"],
    "印第安納波利斯國際機場":["https://www.ind.com/"],
    "狄蒙國際機場":[""],
    "辛辛那提/北肯塔基國際機場":["https://www.cvgairport.com/"],
    "紐奧良路易阿姆斯壯國際機場":["https://flymsy.com/"],
    "巴爾的摩/華盛頓瑟古德·馬歇爾國際機場":["https://bwiairport.com/"],
    "愛德華·勞倫斯·洛根將軍國際機場":["https://www.massport.com/logan-airport"],
    "底特律都會韋恩縣機場":["https://www.metroairport.com/"],
    "聖路易斯蘭伯特國際機場":["https://www.flystl.com/"],
    "哈利·瑞德國際機場":["https://www.harryreidairport.com/"],
    "紐華克自由國際機場":["https://www.newarkairport.com/"],
    "阿布奎基國際機場":["https://www.abqsunport.com/"],
    "約翰·甘迺迪國際機場":["https://www.jfkairport.com/"],
    "克里夫蘭霍普金斯國際機場":["https://www.clevelandairport.com/"],
    "約翰·格倫哥倫布國際機場":["https://flycolumbus.com/"],
    "波特蘭國際機場":["https://www.flypdx.com/"],
    "費城國際機場":["https://www.phl.org/"],
    "匹茲堡國際機場":["https://flypittsburgh.com/"],
    "羅德島T·F·格林國際機場":["https://flyri.com/"],
    "奧斯汀-伯格史東國際機場":["https://www.austintexas.gov/airport"],
    "達拉斯/沃斯堡國際機場":["https://www.dfwairport.com/"],
    "喬治·布希洲際機場":["https://www.fly2houston.com/iah/"],
    "聖安東尼奧國際機場":["https://flysanantonio.com/"],
    "鹽湖城國際機場":["https://slcairport.com/"],
    "諾福克國際機場":["https://www.flyorf.com/"],
    "里契蒙國際機場":["https://flyrichmond.com/"],
    "隆納·雷根華盛頓國家機場":["https://www.flyreagan.com/"],
    "華盛頓杜勒斯國際機場":["https://www.flydulles.com/"],
    "西雅圖-塔科馬國際機場":["https://www.portseattle.org/sea-tac"],
    "亨丁頓三州機場":["https://www.tristateairport.com/" ],
    "拉勒米區域機場":["https://www.flylaramie.com/" ],
    "謝里登機場":["https://www.traveloka.com/en-en/flight/airport/shr"], 
    "安東尼奧·汪帕特國際機場":["https://www.guamairport.com/"], 
    "塞班國際機場":["http://cpa.gov.mp/spnapt.asp" ],
    "路易斯·穆尼奧斯·馬林國際機場":["https://aeropuertosju.com/"], 
    "新加坡樟宜國際機場":["https://www.changiairport.com/"],
    "實里達機場":["https://www.seletarairport.com/"],
    "澳門國際機場":["https://www.macau-airport.com/"],
    "蘭卡威國際機場":["https://www.malaysiaairports.com.my/"],
    "檳城國際機場":["https://penangairport.com/"],
    "怡保國際機場":["https://www.malaysiaairports.com.my/"],
    "蘇丹阿末沙機場":[""],
    "吉隆坡國際機場":["https://airports.malaysiaairports.com.my/"],
    "亞庇國際機場":["https://www.kotakinabaluairport.com/"],
    "蘇丹阿都阿兹沙機場":["https://www.subangskypark.com/"],
    "馬六甲國際機場":["https://www.malaysiaairports.com.my/"],
    "士乃國際機場":["https://www.senaiairport.com/"],
    "斗湖機場":["https://www.malaysiaairports.com.my/"],
    "古晉國際機場":["https://airports.malaysiaairports.com.my/"],
    "美里機場":["https://www.miriairport.com/"],
    "中華航空":["https://www.china-airlines.com/","https://www.facebook.com/chinaairlines.travelchannel"],
    "長榮航空":["https://www.evaair.com/","https://www.facebook.com/evaairwayscorp.tw"],
    "台灣虎航":["https://www.tigerairtw.com/","https://www.facebook.com/TigerairTaiwan"],
    "星宇航空":["https://www.starlux-airlines.com/","https://www.facebook.com/starluxairlines"],
    "日本航空":["https://www.jal.co.jp/"],
    "全日本空輸":["https://www.ana.co.jp/zh/tw/"],
    "捷星日本航空":["https://www.jetstar.com/tw/zh/"],
    "樂桃航空":["https://www.flypeach.com/tw/"],
    "山東航空":["https://global.sda.cn/tw/tc/"],
    "中國東方航空":["https://tw.ceair.com/hk/"],
    "中國南方航空":["https://www.csair.com/tw/tc/"],
    "中國國際航空":["https://www.airchina.com.cn/zh-TW"],
    "四川航空": ["https://www.sichuanair.com/"],
    "春秋航空": ["https://hk.ch.com/"],
    "海南航空": ["https://www.hainanairlines.com/TW/TW/"],
    "深圳航空": ["https://global.shenzhenair.com/"],
    "廈門航空": ["https://www.xiamenair.com/tw-tw/"],
    "吉祥航空": ["https://www.juneyaoair.com/"],
    "大韓航空": ["https://www.koreanair.com/"],
    "可依航空": ["https://www.aerok.com/zh-TW/"],
    "易斯達航空": ["https://www.eastarjet.com/"],
    "首爾航空": ["https://flyairseoul.com/CW/zh/"],
    "真航空": ["https://www.jinair.com/"],
    "釜山航空": ["https://tw.airbusan.com/"],
    "德威航空": ["https://www.twayair.com/"],
    "濟州航空": ["https://www.jejuair.net/zh-tw/"],
    "韓亞航空": ["https://flyasiana.com/C/TW/ZH/"],
    "越竹航空": ["https://www.bambooairways.com/tw/tw/"],
    "越南航空": ["https://www.vietnamairlines.com/tw/zh-tw/"],
    "越旅航空": ["https://www.vietravelairlines.com/us/tw/"],
    "越捷航空": ["https://www.vietjetair.com/zh-TW/"],
    "大灣區航空": ["https://www.greaterbay-airlines.com/tw/zh_TW/"],
    "香港快運航空": ["https://www.hkexpress.com/zh-TW/"],
    "香港航空": ["https://www.hongkongairlines.com/zh_TW/"],
    "國泰航空": ["https://www.cathaypacific.com/cx/zh_TW/"],
    "泰國亞洲航空": ["https://www.airasia.com/zh/tw"],
    "泰國航空": ["https://www.thaiairways.com/zh-tw/"],
    "泰國越捷航空": ["https://www.vietjetair.com/zh-TW/"],
    "泰國獅子航空": ["https://www.lionairthai.com/tw/tw/"],
    "達美航空": ["https://zt.delta.com/apac/zt"],
    "聯合航空": ["https://www.united.com/zh-hant/tw/"],
    "新加坡航空": ["https://www.singaporeair.com/zh_TW/tw/"],
    "酷航空": ["https://www.flyscoot.com/zhtw/"],
    "澳門航空": ["https://www.airmacau.com.mo/"],
    "亞洲航空": ["https://www.airasia.com/"],
    "馬來西亞航空": ["https://www.malaysiaairlines.com/tw/zh_tw/"],
    "護照": ["https://www.boca.gov.tw/","https://www.facebook.com/mofa.gov.tw"],
    "台北關": ["https://web.customs.gov.tw/taipei/","https://www.facebook.com/taipei.customs.gov.tw","https://www.cdc.gov.tw/","https://www.aphia.gov.tw/","https://www.facebook.com/aphia.tw"],
    "台中關": ["https://web.customs.gov.tw/taichung/","https://www.facebook.com/TCCcustoms"],
    "高雄關": ["https://web.customs.gov.tw/kaohsiung","https://www.facebook.com/KHHcustoms"],
    "日本": ["https://services.digital.go.jp/visit-japan-web/" ,"https://www.mofa.go.jp/" ,"https://www.customs.go.jp/","https://www.moj.go.jp/","https://www.japan.travel/","https://www.maff.go.jp/","https://www.maff.go.jp/pps/","https://www.studyinjapan.go.jp/","https://www.jnto.go.jp/"],
    "中國": ["http://xiamen.customs.gov.cn/","https://www.sef.org.tw/","https://www.caac.gov.cn/","https://www.hlhbsc.org/","https://s.nia.gov.cn/","http://www.customs.gov.cn/","https://www.kma.gov.tw/"],
    "香港": ["https://www.gov.hk/","https://www.immd.gov.hk/","https://www.customs.gov.hk/"],
    "越南": ["https://vietnam.gov.vn/","https://www.vietnam-evisa.org/","https://vietnamembassy-philippines.org/","https://xuatnhapcanh.gov.vn/","https://evisa.xuatnhapcanh.gov.vn/","https://www.boca.gov.tw/","https://www.visitvietnamvisa.com/","https://evisa.gov.vn/","https://www.roc-taiwan.org/","https://www.kkday.com/","https://www.vietnam-visa.com/","https://www.mofa.gov.vn/"],
    "泰國": ["https://www.thaiembassy.org/","https://www.thaievisa.go.th/","https://www.siam-legal.com/","https://www.customs.go.th/","https://en.fda.moph.go.th/","https://www.tourismthailand.org/","https://www.tattpe.org.tw/","https://www.thailand.go.th/","https://tdac.immigration.go.th/"],
    "馬來西亞": ["https://www.boca.gov.tw/","https://www.customs.gov.my/en/","https://www.kln.gov.my/","https://rai.malaysia.gov.my/","https://www.imi.gov.my/","https://www.doa.gov.my/","https://www.promotemalaysia.com.tw/","https://apply.joinsherpa.com/","https://www.maybank2u.com.my/","https://www.jpn.gov.my/","https://www.sppim.gov.my/"],
    "新加坡": ["https://www.nparks.gov.sg/","https://www.mom.gov.sg/","https://www.customs.gov.sg/","https://www.ica.gov.sg/","https://www.boca.gov.tw/"],
    "南韓": ["https://www.immigration.go.kr/","https://www.qia.go.kr/","https://www.airport.kr/","https://big5chinese.visitkorea.or.kr/","https://www.avsec365.or.kr/","https://www.customs.go.kr/","https://www.k-eta.go.kr/","https://www.visa.go.kr/","https://www.hikorea.go.kr/","https://e-arrivalcard.go.kr/","https://taiwan.mofa.go.kr/"],
    "澳門": ["https://www.customs.gov.mo/","https://www.fsm.gov.mo/","https://www.gov.mo/","https://www.kma.gov.tw/"],
    "美國": ["https://www.boca.gov.tw/","https://www.usimmigrationsupport.org/","https://www.usa.gov/","https://www.state.gov/","https://www.uscis.gov/","https://www.usda.gov/","https://www.cbp.gov/","https://www.aphis.usda.gov/","https://travel.state.gov/"]
}